---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aws-quota
  namespace: argoapp
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: default
    server: '*'
  sourceRepos:
  - https://github.com/cpwc/aws-quota-checker
  - https://github.com/abhatia05/k8s-test
